import type { ThemeConfig } from 'tailwindcss/types/config'

export const fontFamily: ThemeConfig['fontFamily'] = {
  'playwrite-cu-extra-light': 'PlaywriteCU-ExtraLight',
  'playwrite-cu-light': 'PlaywriteCU-Light',
  'playwrite-cu-regular': 'PlaywriteCU-Regular',
  'playwrite-cu-thin': 'PlaywriteCU-Thin',
  'roboto-black': 'Roboto-Black',
  'roboto-black-italic': 'Roboto-BlackItalic',
  'roboto-bold': 'Roboto-Bold',
  'roboto-bold-italic': 'Roboto-BoldItalic',
  'roboto-italic': 'Roboto-Italic',
  'roboto-light': 'Roboto-Light',
  'roboto-light-italic': 'Roboto-LightItalic',
  'roboto-medium': 'Roboto-Medium',
  'roboto-medium-italic': 'Roboto-MediumItalic',
  'roboto-regular': 'Roboto-Regular',
  'roboto-thin': 'Roboto-Thin',
  'roboto-thin-italic': 'Roboto-ThinItalic',
  'noto-sans-bold': 'NotoSans-Bold',
  'noto-sans-regular': 'NotoSans-Regular',
  'noto-sans-semi-bold': 'NotoSans-SemiBold',
  'noto-sans-medium': 'NotoSans-Medium',
  parastoo: 'Parastoo',
  'parastoo-bold': 'Parastoo-Bold',
}

export const typography = {
  '.typography-h1': {
    fontSize: '96px',
    lineHeight: '96px',
    fontWeight: 700,
    fontFamily: 'parastoo-bold',
  },
  '.typography-h2': {
    fontSize: '64px',
    lineHeight: '70px',
    fontWeight: 700,
    fontFamily: 'parastoo-bold',
  },
  '.typography-h3': {
    fontSize: '48px',
    lineHeight: '56px',
    fontWeight: 700,
    fontFamily: 'parastoo-bold',
  },
  '.typography-h4': {
    fontSize: '32px',
    lineHeight: '40px',
    fontWeight: 700,
    fontFamily: 'parastoo-bold',
  },
  '.typography-h5': {
    fontSize: '24px',
    lineHeight: '30px',
    fontWeight: 700,
    fontFamily: 'parastoo-bold',
  },
  '.typography-h6': {
    fontSize: '20px',
    lineHeight: '24px',
    fontWeight: 700,
    fontFamily: 'parastoo-bold',
  },

  '.typography-subtitle1': {
    fontSize: '24px',
    lineHeight: '30px',
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },
  '.typography-subtitle2': {
    fontSize: '20px',
    lineHeight: '24px',
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },
  '.typography-subtitle3': {
    fontSize: '16px',
    lineHeight: '20px',
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },
  '.typography-subtitle4': {
    fontSize: '14px',
    lineHeight: '18px',
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },
  '.typography-subtitle5': {
    fontSize: '12px',
    lineHeight: '16px',
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },

  '.typography-body1': {
    fontSize: '20px',
    lineHeight: '36px',
    letterSpacing: 0.02,
    fontWeight: 400,
    fontFamily: 'parastoo',
  },
  '.typography-body2': {
    fontSize: '16px',
    lineHeight: '20px',
    letterSpacing: 0.02,
    fontWeight: 400,
    fontFamily: 'parastoo',
  },
  '.typography-body3': {
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: 0.02,
    fontWeight: 400,
    fontFamily: 'parastoo',
  },
  '.typography-body4': {
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: 0.02,
    fontWeight: 400,
    fontFamily: 'parastoo',
  },

  '.typography-buttonLarge': {
    fontSize: '16px',
    lineHeight: '20px',
    letterSpacing: 0.02,
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },
  '.typography-buttonMedium': {
    fontSize: '14px',
    lineHeight: '18px',
    letterSpacing: 0.02,
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },
  '.typography-buttonSmall': {
    fontSize: '12px',
    lineHeight: '14px',
    letterSpacing: 0.02,
    fontWeight: 600,
    fontFamily: 'parastoo-bold',
  },

  '.typography-caption1': {
    fontSize: '14px',
    lineHeight: '18px',
    fontWeight: 500,
    fontFamily: 'parastoo',
  },
  '.typography-caption2': {
    fontSize: '12px',
    lineHeight: '16px',
    fontWeight: 500,
    fontFamily: 'parastoo',
  },
  '.typography-caption3': {
    fontSize: '10px',
    lineHeight: '12px',
    fontWeight: 500,
    fontFamily: 'parastoo',
  },

  '.typography-overline1': {
    fontSize: '14px',
    lineHeight: '18px',
    fontWeight: 700,
    letterSpacing: 0.04,
    fontFamily: 'parastoo-bold',
  },
  '.typography-overline2': {
    fontSize: '12px',
    lineHeight: '16px',
    fontWeight: 700,
    letterSpacing: 0.04,
  },
  '.typography-overline3': {
    fontSize: '10px',
    lineHeight: '12px',
    fontWeight: 700,
    letterSpacing: 0.04,
  },
}
